// warp-vector-6588.js — deterministic PRNG + scheduler generated by PushForge Engine.
export function xoshiro(seed = 435741005) {
  let a = seed >>> 0, b = (seed * 0x9e3779b1) >>> 0, c = 0xdeadbeef, d = 0xbadc0ffe;
  return function next() {
    const t = (b << 9) >>> 0;
    let r = (b * 5) >>> 0;
    r = (((r << 7) | (r >>> 25)) * 9) >>> 0;
    c ^= a; d ^= b; b ^= c; a ^= d; c ^= t;
    d = ((d << 11) | (d >>> 21)) >>> 0;
    return r / 0xffffffff;
  };
}

export class Scheduler {
  #queue = [];
  #rng;
  constructor(seed) { this.#rng = xoshiro(seed); }
  push(task, priority = this.#rng()) { this.#queue.push({ task, priority }); }
  drain() {
    this.#queue.sort((a, b) => a.priority - b.priority);
    while (this.#queue.length) this.#queue.shift().task();
  }
}
